INSERT INTO cinema VALUES(1, 'Paula','The great cinema 1');
INSERT INTO cinema VALUES(2, 'San Giljan, Sliema','The great cinema 2');
INSERT INTO theatre VALUES(1, 'Screen 1', 1);
INSERT INTO theatre VALUES(2, 'Screen 2', 1);
INSERT INTO theatre VALUES(3, 'Screen 3', 2);
INSERT INTO film VALUES(7, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',  'Avengers: Infinity War');
INSERT INTO film VALUES(8, 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'The Godfather');
INSERT INTO theatre_film VALUES(1, 7, 1);
INSERT INTO theatre_film VALUES(2, 8, 1);
INSERT INTO theatre_film VALUES(3, 7, 2);

INSERT INTO seat VALUES (1, 1, 1);
INSERT INTO seat VALUES (2, 1, 1);
INSERT INTO seat VALUES (3, 1, 1);
INSERT INTO seat VALUES (4, 1, 1);
INSERT INTO seat VALUES (5, 1, 1);
INSERT INTO seat VALUES (6, 1, 1);
INSERT INTO seat VALUES (7, 2, 1);
INSERT INTO seat VALUES (8, 2, 1);
INSERT INTO seat VALUES (9, 2, 1);
INSERT INTO seat VALUES (10, 2, 1);
INSERT INTO seat VALUES (11, 2, 1);
INSERT INTO seat VALUES (12, 2, 1);
INSERT INTO seat VALUES (13, 3, 1);
INSERT INTO seat VALUES (14, 3, 1);
INSERT INTO seat VALUES (15, 3, 1);
INSERT INTO seat VALUES (16, 3, 1);
INSERT INTO seat VALUES (17, 3, 1);
INSERT INTO seat VALUES (18, 3, 1);
INSERT INTO seat VALUES (19, 4, 1);
INSERT INTO seat VALUES (20, 4, 1);
INSERT INTO seat VALUES (21, 4, 1);
INSERT INTO seat VALUES (22, 4, 1);
INSERT INTO seat VALUES (23, 4, 1);
INSERT INTO seat VALUES (24, 4, 1);
INSERT INTO seat VALUES (25, 5, 1);
INSERT INTO seat VALUES (26, 5, 1);
INSERT INTO seat VALUES (27, 5, 1);
INSERT INTO seat VALUES (28, 5, 1);
INSERT INTO seat VALUES (29, 5, 1);
INSERT INTO seat VALUES (30, 5, 1);
INSERT INTO seat VALUES (31, 6, 1);
INSERT INTO seat VALUES (32, 6, 1);
INSERT INTO seat VALUES (33, 6, 1);
INSERT INTO seat VALUES (34, 6, 1);
INSERT INTO seat VALUES (35, 6, 1);
INSERT INTO seat VALUES (36, 6, 1);
INSERT INTO seat VALUES (37, 7, 1);
INSERT INTO seat VALUES (38, 7, 1);
INSERT INTO seat VALUES (39, 7, 1);
INSERT INTO seat VALUES (40, 7, 1);
INSERT INTO seat VALUES (41, 7, 1);
INSERT INTO seat VALUES (42, 7, 1);
INSERT INTO seat VALUES (43, 8, 1);
INSERT INTO seat VALUES (44, 8, 1);
INSERT INTO seat VALUES (45, 8, 1);
INSERT INTO seat VALUES (46, 8, 1);
INSERT INTO seat VALUES (47, 8, 1);
INSERT INTO seat VALUES (48, 8, 1);
INSERT INTO seat VALUES (49, 9, 1);
INSERT INTO seat VALUES (50, 9, 1);
INSERT INTO seat VALUES (51, 9, 1);
INSERT INTO seat VALUES (52, 9, 1);
INSERT INTO seat VALUES (53, 9, 1);
INSERT INTO seat VALUES (54, 9, 1);
INSERT INTO seat VALUES (55, 10, 1);
INSERT INTO seat VALUES (56, 10, 1);
INSERT INTO seat VALUES (57, 10, 1);
INSERT INTO seat VALUES (58, 10, 1);
INSERT INTO seat VALUES (59, 10, 1);
INSERT INTO seat VALUES (60, 10, 1);

INSERT INTO seat VALUES (61, 1, 2);
INSERT INTO seat VALUES (62, 1, 2);
INSERT INTO seat VALUES (63, 1, 2);
INSERT INTO seat VALUES (64, 1, 2);
INSERT INTO seat VALUES (65, 1, 2);
INSERT INTO seat VALUES (66, 1, 2);
INSERT INTO seat VALUES (67, 2, 2);
INSERT INTO seat VALUES (68, 2, 2);
INSERT INTO seat VALUES (69, 2, 2);
INSERT INTO seat VALUES (70, 2, 2);
INSERT INTO seat VALUES (71, 2, 2);
INSERT INTO seat VALUES (72, 2, 2);
INSERT INTO seat VALUES (73, 3, 2);
INSERT INTO seat VALUES (74, 3, 2);
INSERT INTO seat VALUES (75, 3, 2);
INSERT INTO seat VALUES (76, 3, 2);
INSERT INTO seat VALUES (77, 3, 2);
INSERT INTO seat VALUES (78, 3, 2);

INSERT INTO booking VALUES(1, 1);
INSERT INTO booking VALUES(1, 2);
INSERT INTO booking VALUES(1, 4);
INSERT INTO booking VALUES(3, 61);
INSERT INTO booking VALUES(3, 64);