INSERT INTO cinema VALUES(1,'addressDemo','demoName');
INSERT INTO theatre VALUES(1, 'theatreDemo', 1);
INSERT INTO film VALUES(7, 'Avengers: Infinity War ', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.');
INSERT INTO theatre_film VALUES(1, 7, 1);
-- INSERT INTO theatre_film VALUES(3, 123, 1);
-- INSERT INTO booking VALUES(1, 1);
INSERT INTO seat VALUES (1, 'A1', 1);
INSERT INTO seat VALUES (2, 'A2', 1);
INSERT INTO seat VALUES (3, 'A3', 1);
INSERT INTO seat VALUES (4, 'A4', 1);
INSERT INTO seat VALUES (5, 'A5', 1);
INSERT INTO seat VALUES (6, 'A6', 1);
INSERT INTO seat VALUES (7, 'B1', 1);
INSERT INTO seat VALUES (8, 'B2', 1);
INSERT INTO seat VALUES (9, 'B3', 1);
INSERT INTO seat VALUES (10, 'B4', 1);
INSERT INTO seat VALUES (11, 'B5', 1);
INSERT INTO seat VALUES (12, 'B6', 1);
INSERT INTO seat VALUES (13, 'C1', 1);
INSERT INTO seat VALUES (14, 'C2', 1);
INSERT INTO seat VALUES (15, 'C3', 1);
INSERT INTO seat VALUES (16, 'C4', 1);
INSERT INTO seat VALUES (17, 'C5', 1);
INSERT INTO seat VALUES (18, 'C6', 1);
INSERT INTO seat VALUES (19, 'D1', 1);
INSERT INTO seat VALUES (20, 'D2', 1);
INSERT INTO seat VALUES (21, 'D3', 1);
INSERT INTO seat VALUES (22, 'E1', 1);
INSERT INTO seat VALUES (23, 'E2', 1);
INSERT INTO seat VALUES (24, 'E3', 1);
INSERT INTO seat VALUES (25, 'E4', 1);
INSERT INTO seat VALUES (26, 'F1', 1);
INSERT INTO seat VALUES (27, 'F2', 1);
INSERT INTO seat VALUES (28, 'F3', 1);
INSERT INTO seat VALUES (29, 'F4', 1);
INSERT INTO seat VALUES (30, 'G1', 1);
INSERT INTO seat VALUES (31, 'G2', 1);
INSERT INTO seat VALUES (32, 'G3', 1);
INSERT INTO seat VALUES (33, 'G4', 1);
INSERT INTO seat VALUES (34, 'G5', 1);
INSERT INTO seat VALUES (35, 'G6', 1);
INSERT INTO seat VALUES (36, 'H1', 1);
INSERT INTO seat VALUES (37, 'H2', 1);
INSERT INTO seat VALUES (38, 'H3', 1);
INSERT INTO seat VALUES (39, 'H4', 1);
INSERT INTO seat VALUES (40, 'H5', 1);
INSERT INTO seat VALUES (41, 'H6', 1);
INSERT INTO seat VALUES (42, 'I1', 1);
INSERT INTO seat VALUES (43, 'I2', 1);
INSERT INTO seat VALUES (44, 'I3', 1);
INSERT INTO seat VALUES (45, 'I4', 1);
INSERT INTO seat VALUES (46, 'I5', 1);
INSERT INTO seat VALUES (47, 'I6', 1);
INSERT INTO seat VALUES (48, 'J1', 1);
INSERT INTO seat VALUES (49, 'J2', 1);
INSERT INTO seat VALUES (50, 'J3', 1);
INSERT INTO seat VALUES (51, 'J4', 1);
INSERT INTO seat VALUES (52, 'J5', 1);
INSERT INTO seat VALUES (53, 'J6', 1);
INSERT INTO seat VALUES (54, 'K1', 1);
INSERT INTO seat VALUES (55, 'K2', 1);
INSERT INTO seat VALUES (56, 'K3', 1);
INSERT INTO seat VALUES (57, 'K4', 1);
INSERT INTO seat VALUES (58, 'K5', 1);
INSERT INTO seat VALUES (59, 'K6', 1);

INSERT INTO booking VALUES(1, 1);
INSERT INTO booking VALUES(1, 2);